services:
  - type: web
    name: docsage-api
    env: node
    rootDir: api
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.17.0
    autoDeploy: true
